sudo: required
services:
  - docker

before_install:
  - docker build -t valdivieso01/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run valdivieso01/react-test npm test -- --coverage

after_success:
  - docker_build -t valdivieso01/multi-client ./client
  - docker_build -t valdivieso01/multi-nginx ./nginx
  - docker_build -t valdivieso01/multi-server ./server
  - docker_build -t valdivieso01/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push valdivieso01/multi-client
  - docker push valdivieso01/multi-nginx
  - docker push valdivieso01/multi-server
  - docker push valdivieso01/multi-worker

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-sa-east-1-378140284032 
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
