sudo: required
services:
  - docker

before_install:
  - docker build -t react-test ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm test -- --coverage

after_success:
  - docker_build -t multi-client ./client
  - docker_build -t multi-nginx ./nginx
  - docker_build -t multi-server ./server
  - docker_build -t multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push multi-client
  - docker push multi-nginx
  - docker push multi-server
  - docker push multi-worker

